name: CI
on: [push, pull_request]
jobs:

  build-alpine-docker-musl-gcc:
    runs-on: ubuntu-latest
    name: Alpine/musl
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build V
      using: 'docker'
      image: Dockerfile.alpine
      entrypoint: .github/workflows/alpine.build.sh

    - name: Test V
      using: 'docker'
      image: Dockerfile.alpine
      entrypoint: .github/workflows/alpine.test.sh
