name: Alpine Docker 
on: [push, pull_request]
jobs:

  build-alpine-docker-musl-gcc:
    runs-on: ubuntu-latest
    name: An Alpine docker build of V
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Make & Test V
      uses: spytheman/docker_alpine_v@v4.0
      with:
        entrypoint: .github/workflows/alpine.sh
