name: CI
on: [push, pull_request]
jobs:

  build-alpine-docker-musl-gcc:
    name: Alpine/musl
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build V
      uses: vlang/v@master
      using: 'docker'
      image: 'Dockerfile.alpine'
      entrypoint: .github/workflows/alpine.build.sh

    - name: Test V
      uses: vlang/v@master
      using: 'docker'
      image: 'Dockerfile.alpine'
      entrypoint: .github/workflows/alpine.test.sh
