name: Build master - Linux

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]

    steps:
    - uses: actions/checkout@v1
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: make
    - name: Create artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: .
