name: Cancel previous workflows

on:
  workflow_run:
    workflows: ["Code CI", "Sanitized CI"] # the other workflows finish quickly - no need to skip them for now
    types:
      - requested

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
