name: CI
on: [push, pull_request]
jobs:


  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        brew update
        brew install freetype glfw openssl postgres sdl2 sdl2_ttf sdl2_mixer sdl2_image
        export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib/"
    - name: Set up pg database
      run: |
        pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
        sleep 3
        cat /usr/local/var/postgres/server.log
        psql -d postgres -c 'select rolname from pg_roles'
        psql -d postgres -c 'create database customerdb;'
        psql -d customerdb -f examples/database/pg/mydb.sql