name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  windows-tcc:
    runs-on: windows-2019
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build with make.bat -tcc
        run: .\make.bat -tcc
      - name: Install dependencies
        run: |
          .\v.exe setup-freetype
          .\.github\workflows\windows-install-sqlite.bat
          ## .\.github\workflows\windows-install-sdl.bat
      - name: v doctor
        run: ./v doctor
      - name: Verify `v test` works
        run: |
          .\v.exe cmd/tools/test_if_v_test_system_works.v
          .\cmd\tools\test_if_v_test_system_works.exe
      - name: Make sure running TCC64 instead of TCC32
        run : .\v.exe test .github\workflows\make_sure_ci_run_with_64bit_compiler_test.v
        
      - name: Test ./v doc -v clipboard *BEFORE building tools*
        run: ./v doc -v clipboard
        
      - name: Test v build-tools
        run: ./v -W build-tools
        
      - name: Test ./v doc -v clipboard
        run: ./v doc -v clipboard

  ## tcc32
      - name: Build with make.bat -tcc32
        run: |
          Remove-Item -Recurse -Force .\thirdparty\tcc
          .\v.exe wipe-cache
          .\make.bat -tcc32
      - name: v doctor
        run: ./v doctor
      - name: Verify `v test` works
        run: |
          .\v.exe cmd/tools/test_if_v_test_system_works.v
          .\cmd\tools\test_if_v_test_system_works.exe
      - name: Make sure running TCC32 instead of TCC64
        run : .\v.exe test .github\workflows\make_sure_ci_run_with_32bit_compiler_test.v
      - name: Test v build-tools
        run: ./v -W build-tools

      - name: Test ./v doc -v clipboard
        run: ./v doc -v clipboard
