name: Docs CI

on:
  push:
    paths:
      - ".github/workflows/docs_ci.yml"
      - "cmd/tools/check-md.v"
      - "**.md"
  pull_request:
    paths:
      - ".github/workflows/docs_ci.yml"
      - "cmd/tools/check-md.v"
      - "**.md"

jobs:
  docs-line-len-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build V
      run: make
    - name: Check docs line length & code examples
      run: |
        ./v run cmd/tools/check-md.v doc/docs.md doc/upcoming.md
        ./v run cmd/tools/check-md.v CHANGELOG.md  CODE_OF_CONDUCT.md CONTRIBUTING.md README.md TESTS.md
        ./v run cmd/tools/check-md.v tutorials/building-a-simple-web-blog-with-vweb.md
        ./v run cmd/tools/check-md.v vlib/vweb/README.md vlib/pg/README.md vlib/sqlite/README.md vlib/encoding/csv/README.md vlib/rand/README.md vlib/flag/README.md
